version: "3.9"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigration &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./data/web:/vol/web
    depends_on:
      - db
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - djshop-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djshop
      - POSTGRES_USER=djshop
      - POSTGRES_PASSWORD=1234
  redis_cache:
    ports:
      - 6379:6379
  redis_celery:
    ports:
      - 6378:6378
  rabitmq:
    ports:
      - 5672:5672
  meilisearch:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=TESTKEYLOCAL
    volumes:
      - meilisearch-volume:/data.ms
    ports:
      - 7700:7700

volumes:
  djshop-data:
  meilisearch-volume: 
